Use list of points instead of vararg for specifying on the fly trajectories.
mjansen4857/pathplanner pull request #178
Opened 2022-12-14 13:55 UTC by brennenputh

This PR changes the generatePath method to accept a list of PathPoints instead of taking two arguments and a vararg of PathPoints.

The reasoning behind this change is situations like my own, where I would like to be able to pass several points into a function to get a command that runs a path.  Using the PathPlanner generatePath method everywhere would mean unnecessary code duplication of the constraints.  This causes me to have to write ugly code in order to accept a list of points, getting the first two by index and then calling subList and converting that sub list to an array.

The secondary reasoning is that the paths are simply reconstructed into an ArrayList at the end of the day already.  It doesn't make sense to convert away from a List back into a List.

As other options on this PR, I'm unsure whether it would be better to keep a vararg overload.  If this is desired, I can add one.  Also, it may be easier to add overloads that take Lists, however this adds a lot of unnecessary code for the Lists to be turned into arrays for varargs to be turned right back into a List.

Feel free to deny if this is actively not desired.

2022-12-17 18:57 UTC, mjansen4857 commented
Instead of replacing the methods, I would prefer overloads. Using varargs makes it a bit cleaner to use in some cases so I'd like to keep that option.

For example:
```Java
generatePath(constraints, currentRobotPoint, loadingStationPoint);
```

vs

```Java
generatePath(constraints, List.of(currentRobotPoint, loadingStationPoint));
```

It just removes the need to create a list yourself. All the vararg overload would need to do is create the list for you.

2022-12-18 01:15 UTC, brennenputh commented
Added in latest commit.  I do have one question, what is the point of having a overload with the max velocity and max acceleration broken out instead of passed in as PathConstraints?  It seems like it adds a lot of overloads for not much gain.

2022-12-18 01:48 UTC, brennenputh commented
One other thing, would it be wise to implement the same change in C++?  I am inexperienced in C++ so I am unsure if there is a standard.

2022-12-18 23:19 UTC, mjansen4857 commented
C++ could benefit from doing the same thing, just vectors and initializer lists instead of lists and varargs. I could take care of that though if you'd like.

2022-12-19 00:49 UTC, brennenputh commented
I'll get the C++ changes done, they don't look hard from a glance.  I'll also make sure to mark the separate vel/accel as deprecated.

2022-12-19 01:42 UTC, brennenputh commented
Looked around, I'm not sure what to use as the equivalent of deprecated in C++.  Other than that though, I believe it's done.

2022-12-19 01:57 UTC, mjansen4857 commented
It looks like you can do deprecation in C++ like this:
```C++
[[deprecated("Use someOtherMethod() instead.")]]
void deprecatedMethod() {}
```

Haven't bothered to try to compile it with the roborio toolchain so if it fails to build then no big deal.

2022-12-19 02:08 UTC, brennenputh commented
Done.

2022-12-19 21:33 UTC, mjansen4857 requested changes

2022-12-19 21:33 UTC, mjansen4857 commented on pathplannerlib/src/main/native/include/pathplanner/lib/PathPlanner.h
> +	static PathPlannerTrajectory generatePath(
Missed a deprecation here

2022-12-19 21:33 UTC, mjansen4857 commented on pathplannerlib/src/main/native/include/pathplanner/lib/PathPlanner.h
> +	;
This looks like a random semicolon

2022-12-20 00:11 UTC, merged

2022-12-29 06:04 UTC, auscompgeek commented
Could we get another release with this change in? Currently looking at updating the RobotPy bindings for 2023 and noticed the `generatePath` method is unusable from our end.

2022-12-29 06:55 UTC, virtuald commented
To explain (and keep in mind for the future): RobotPy cannot use std::initializer_list since the list has to be known at compile time, so anything that uses that needs a different overload that takes a span or a vector or whatever otherwise RobotPy cannot use it. Thanks!

2022-12-29 16:38 UTC, mjansen4857 commented
Sure thing. I will look through everything to make sure there are initializer list alternatives and then push a PPLib update at least.

2022-12-29 17:16 UTC, mjansen4857 commented
OK update is now available. If there are any other issues with RobotPy support that need changes feel free to open an issue and I'll take a look.